### ISSUE TITLE
There is no way to delete an individual history item

### ISSUE THREAD

**Issue by sgpthomas** [stuartlangridge/ColourPicker#8] opened 2016-05-27 16:55 UTC
As far as I can tell, there is only a way to clear all history. I think it would be nice to delete individual history items

**Comment by stuartlangridge** [comment] 2016-05-27 16:57
Yup. By design, because individual deletion of items would clutter the UI. I'm happy to hear suggestions for how to do this _without_ cluttering the UI if anyone has them, but in the absence of such suggestions, Pick having a simple clear UI is important and so wontfix.

**Closed as completed** 2016-05-29 10:30 UTC
Labels: wontfix
